name: Build & Push Backend Image and Deploy

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME_BACKEND }}
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build backend jar
        working-directory: ./backend
        run: mvn -B -f pom.xml clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App to use new Docker image
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}