name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
      BACKEND_IMAGE_NAME: ${{ secrets.BACKEND_IMAGE_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SQL_ADMIN_PASSWORD=${{ env.SQL_ADMIN_PASSWORD }} \
            -t ${{ env.BACKEND_IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ env.BACKEND_IMAGE_NAME }}:latest