name: Deploy Terraform Infra

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform   # <<< هذا أهم شي!

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
          ARM_TENANT_ID: ${{ secrets.TENANTID }}
        run: |
          terraform plan \
            -var="sql_admin_user=${{ secrets.SQL_ADMIN_USER }}" \
            -var="sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" \
            -var="sql_db_name=${{ secrets.SQL_DB_NAME }}" \
            -out=tfplan

      - name: Terraform Apply
        if: success()
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
          ARM_TENANT_ID: ${{ secrets.TENANTID }}
        run: terraform apply -auto-approve tfplan