name: Terraform Infra Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
      ARM_TENANT_ID: ${{ secrets.TENANTID }}
      SQL_ADMIN_USER: ${{ secrets.SQL_ADMIN_USER }}
      SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
      SQL_DB_NAME: ${{ secrets.SQL_DB_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Format
        working-directory: infra/terraform
        run: terraform fmt -recursive

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/terraform
        run: |
          terraform plan \
            -var="sql_admin_user=${{ env.SQL_ADMIN_USER }}" \
            -var="sql_admin_password=${{ env.SQL_ADMIN_PASSWORD }}" \
            -var="sql_db_name=${{ env.SQL_DB_NAME }}" \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan